lib: [
  "_build/install/default/lib/camelsnakekebab/META" {"META"}
  "_build/install/default/lib/camelsnakekebab/camelsnakekebab.a" {"camelsnakekebab.a"}
  "_build/install/default/lib/camelsnakekebab/camelsnakekebab.cma" {"camelsnakekebab.cma"}
  "_build/install/default/lib/camelsnakekebab/camelsnakekebab.cmi" {"camelsnakekebab.cmi"}
  "_build/install/default/lib/camelsnakekebab/camelsnakekebab.cmt" {"camelsnakekebab.cmt"}
  "_build/install/default/lib/camelsnakekebab/camelsnakekebab.cmti" {"camelsnakekebab.cmti"}
  "_build/install/default/lib/camelsnakekebab/camelsnakekebab.cmx" {"camelsnakekebab.cmx"}
  "_build/install/default/lib/camelsnakekebab/camelsnakekebab.cmxa" {"camelsnakekebab.cmxa"}
  "_build/install/default/lib/camelsnakekebab/camelsnakekebab.cmxs" {"camelsnakekebab.cmxs"}
  "_build/install/default/lib/camelsnakekebab/camelsnakekebab.dune" {"camelsnakekebab.dune"}
  "_build/install/default/lib/camelsnakekebab/camelsnakekebab.ml" {"camelsnakekebab.ml"}
  "_build/install/default/lib/camelsnakekebab/camelsnakekebab.mli" {"camelsnakekebab.mli"}
  "_build/install/default/lib/camelsnakekebab/opam" {"opam"}
]
doc: [
  "_build/install/default/doc/camelsnakekebab/README.md"
]
